### ISSUE TITLE
RDS Ideas

### ISSUE THREAD

**Issue by flobaader** [pellepelster/solidblocks#12]
Hi @pellepelster,

thanks for the awesome work for running Postgres VMs on Hetzner! That was also a big issue for us, because we want to have the comfort of managed RDS in our own cloud. I think that is a very important missing piece in the Hetzner Landscape.
I have a few ideas for the RDS and would love to discuss them:

1. Be able to provision an SSL certificate for Postgres if not just shared on an internal network
2. Support Calling a webhook on successful backup: Then we know if a backup task suddenly stops working
3. Allow to install a bunch of extensions, e.g. pg_stat_statements
4. Document how to restore a certain backup, e.g. if the instance was created with terraform
5. Allow to add a monitoring system, such as https://github.com/CrunchyData/pgmonitor or https://github.com/percona/pmm or a postgres prometheus agent.
6. Document what happens if new users and databases are added to the terraform module, are they also created afterwards?
7. Support updates of OS and system? Maybe with watchtower and unattended upgrades?
8. Automatically harden the VM and e.g. install fail2ban

What do you think of all those ideas?

**Comment by pellepelster** [comment]
Thanks for the valuable feedback,

2./4. You are right, the backup part currently is a little under-documented. That's something that needs some work
1./3. You are not the first to ask for those specific enhancements, so this will something I am gonna plan for the next release(s).

5./6./7.8. The general issue here is to avoid the trap of building the jack of all trades which always has the potential to result in an overly complex and hard to debug/maintain/run system. 
My idea here is more to build those separate components in a library-ish-way where each component is small enough to be understandable and testable and find a good way to make it easy to combine those things. 

The SSH hardening for example is a topic that came up multiple times in the past and has lead to this (still unfinished) [component](https://github.com/pellepelster/solidblocks/tree/main/solidblocks-sshd) which aims to be a tested (by sshaudit) minimal and secure ssh configuration. 
I am still working on multiple approaches to those individual components can be combined in an easy way, without creating a testing nightmare.
In the meantime it is always possible to use the [pre](https://pellepelster.github.io/solidblocks/hetzner/rds-postgresql/index.html#input%5c_pre%5c_script) and [post](https://pellepelster.github.io/solidblocks/hetzner/rds-postgresql/index.html#input%5c_post%5c_script) hooks to execute custom code.

**Comment by pellepelster** [comment]
1. could you clarify the SSL provisioning a bit? did you envision the possibility to inject certificates or more like an automatic cert mgmt. using letsencrypt/zerossl/...?
3. this specific extension was already included, see updated documentation at https://pellepelster.github.io/solidblocks/rds/index.html#extensions. do you have any other extensions in mind that is missing?
7. debians [unattended-upgrades](https://wiki.debian.org/UnattendedUpgrades) will automatically be available with v0.1.16

**Comment by flobaader** [comment]
Hi @pellepelster,

thanks for quick and detailed feedback! The SSL provisioning would be awesome with Lets Encrypt (either HTTP or DNS Challenge) or a self signed cert. Important would be auto rotating, so no maintenance should be required.

I definitely agree on the monitor side, I will just deploy that as a separate container. Do you have any experience on monitoring Postgres and can recommend a certain tool?

Last but not least I would be very interested in replication setups to survive a node outage. This can be really complicated. The bitnami postgres docker image offers that: https://github.com/bitnami/containers/blob/main/bitnami/postgresql/README.md
This could be a cool solution for replication: https://github.com/shayonj/pg_easy_replicate

I think the whole project goes in the direction of the Postgres Operators for Kubernetes, like https://cloudnative-pg.io/documentation/1.20/ - see the main Features.

I am also thinking about running this Hetzner Kubernetes Project with a Postgres Operator, this should provide lots of features but is also a huge stack with lots of failure potential instead of running a simple docker container on a VM.

**Comment by pellepelster** [comment]
Hey, 

I just wanted to let you know that basic LetsEncrypt support is now available, see changelog and documentation for more information. 

For the general direction and purpose of the Hetzner module in relation to the other options you mentioned I added some clarification at https://pellepelster.github.io/solidblocks/hetzner/rds-postgresql/index.html#design-goals

**Comment by flobaader** [comment]
@pellepelster wow thats soo awesome!! Thank you very much.

We had another very scary thing happen today. One of our team members deployed a standard postgres database with a weak default password on the default port 5432.

The server was found within one hour, got hacked and started to attack other servers (Netscan) in the Hetzner network. We were alerted by the High CPU Usage from our monitoring system and got a mail from Hetzner because the database was used to attack other servers in the network.

We were really surprised how fast this happened and glad that we were notified by the monitoring system.

Do you think that it would be possible to make the database more resilient agains those attacks? Maybe fail2ban or something else?

**Comment by flobaader** [comment]
@pellepelster I created a new issue for this topic #14
