### ISSUE TITLE
RDS: Allow to create read only users

### ISSUE THREAD

**Issue by flobaader** [pellepelster/solidblocks#13]
Allow to create read-only users for dashboard or monitoring tools

Usecase: We use tools like Metabase to build dashboards for our postgres databases. Tools like this should get another user for the database that only has read-only access. This would be awesome to create with the already given syntax:

```
docker run \
    -e DB_INSTANCE_NAME=instance1 \
    -e DB_DATABASE_db1=database1 \
    -e DB_USERNAME_db1=user1 \
    -e DB_PASSWORD_db1=password1 \
    -e DB_READONLY_USERNAME_db1=password1 \
    -e DB_READONLY_PASSWORD_db1=password1 \
    pellepelster/solidblocks-rds-postgresql:v0.1.18
```

**Comment by pellepelster** [comment]
The readonly use case is something that I also oftensee in PostgreSQL deployments. The issue with integrating this specific case into the automatic database setup is, that the database autosetup was intended to provide a quick start for database instance setup and give the user a database and an admin user for this database to work with.

Adding more logic for user creation/mgmt. would duplicate logic that already exists in more mature tooling like for example this postgres terraform provider https://registry.terraform.io/providers/doctolib/postgresql/latest/docs.

The instance database admin user respectively the instance admin user could be used together with this or other external tooling to provision further users/roles and more fine grained permissions.

This is not very clear for the documentation right now and I think adding an example for this (e.g. how to create a readonly user) would not hurt.
