### ISSUE TITLE
RDS: Protection against Brute Force Attacks

### ISSUE THREAD

**Issue by flobaader** [pellepelster/solidblocks#14]
The postgres server could be attacked to brute force the given password. A module like `auth_delay` or `Fail2Ban` could be used to further secure the postgres server.

**Auth-Delay:**
https://www.postgresql.org/docs/current/auth-delay.html

**Fail2Ban**
It seems to be not as straight forward to implement this:
https://warlord0blog.wordpress.com/2022/09/14/fail2ban-postgresql/

**Change the default port**
Changing a default port is of course no real security but should help against a lot of automated spamming.

**Create Allowlist of hosts**
And filter this using the hba_conf or a UFW firewall to set a list of ip addresses that are allowed to connect to this database instance.

**Comment by flobaader** [comment]
Addition: Right now the VMs created in the hetzner cloud could be configured with the hetzner firewall to achieve an ip allowlist.

**Comment by christoph-buente** [comment]
You can use the `pre_script` or `post_script` to install `fail2ban` on the host level.

**Comment by pellepelster** [comment]
Closing this issue because it is now possible to bind to local interfaces and completely avoid external access. `fail2ban` currently is not in scope and can be added via  `pre_script` and/or `post_script` if needed.
