### ISSUE TITLE
RDS Hetzner: Certificates from production Let's Encrypt

### ISSUE THREAD

**Issue by apricote** [pellepelster/solidblocks#21]
Right now certificates using `solidblocks-hetzner/modules/rds-postgresql` are issued by the [LetsEncrypt staging issuer](https://github.com/pellepelster/solidblocks/blob/34cc60a3a5dcbfd5cc387f6ecc5ec79d89c62827/solidblocks-hetzner/modules/rds-postgresql/user_data.sh#L193). This means that any application connecting to it must either add the Staging CA to its trust store, or ignore certificate validation, both are suboptimal.

For my private deployment I have just [replaced the URL](https://github.com/apricote/solidblocks/commit/f1b0b9a5aed1cb0a901cac5740affd0ade414ab9) with the production URL. This worked for me, but it would be nice to see this change upstream for others to use.

I am not sure about the approach that would be best here, so I opened this issue instead of a PR with my change:

- **Replace URL**: We can replace the staging URL with the production URL (like in my commit), but you probably used the staging URL with a reason.
- **Make it configurable**:
  - **Bool Flag**: We could add a boolean flag `use_staging_letsencrypt` that would switch between the two LetsEncrypt URLs
  - **API URL**: We could add an input `acme_api_url` that can be used with an arbitrary ACME issue, we can then default to staging Lets Encrypt but still allow production LetsEncrypt or even other ACME implementations like ZeroSSL.

**Comment by pellepelster** [comment]
The staging URL is an accidental leftover from the integration tests, which rely on staging certificates to avoid hitting the API quotas when the tests are run in the CI.
I would go for making the URL configurable via `acme_api_url` to allow using other implementations and make LetsEncrypt prod the default.

**Comment by apricote** [comment]
Nice! I will submit a PR with the option then :)
