### ISSUE TITLE
Support for Google Storage

### ISSUE THREAD

**Issue by Levara** [pellepelster/solidblocks#29]
Hi, would it be possible to add support for Google Storage? Using Google Storage S3 compatibility API does not work, I've tried that, and then I found issues on PgBackRest github where they explain that Google's compatibility mode is not fully compatible and does not support some methods that they use. However, they added native support for Google Storage sometime in 2021 IIRC. 

I looked at the code and it doesn't seem too hard to add that, the main problem would be that the design of ENV vars required to start the container wouldn't be as pretty as now. Also, Google Storage requires a JSON file with the credentials, so that file would probably have to be mounted into the container.

**Comment by pellepelster** [comment]
small FYI update: https://github.com/pellepelster/solidblocks/commit/3c71caada99623dcaae5a9da8416ea6f8adc2e06 adds basic google storage backup to the RDS docker image, next step is to make it configurable for the Hetzner RDS module

**Comment by pellepelster** [comment]
the hetzner module part is now also implemented, some documentation is still missing, I am aiming for a release by the end of the week =)

**Comment by pellepelster** [comment]
feature is now released with v0.2.5 https://registry.terraform.io/modules/pellepelster/solidblocks-rds-postgresql/hcloud/0.2.5
